apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdms-verify-prod

labels:
  - pairs:
      app: cdms-verify-prod
    includeSelectors: false

resources:
  - ../../base
  - namespace.yaml
  - pvc.yaml

patches:
  - path: cdms-verify-prod.yaml
