apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdms-verify-dev

commonLabels:
  app: cdms-verify-dev

resources:
- ../../base
- pvc.yaml

patches:
- path: cdms-verify-dev.yaml
